tables:
- name: t_vent_beregning
  table_type: fak
  description: Beregninger i Oppdragssystemet
  check_col: tidspkt_reg
  order_cols: 
    - beregnings_id
  cols:
    - name: beregnings_id
      col_data_type: integer
      description: Unik identifikator for beregninger i Oppdragssystemet.
      mode: required

    - name: dato_beregnet
      col_data_type: date
      description: Datoen beregningen er utført i Oppdragssystemet.
      mode: required

    - name: kode_faggruppe
      col_data_type: string
      description: Kode for faggruppe. En faggruppe består av flere fagområder hvor man ønsker en samlet felles skatt- og trekkberegning. F.eks. 'PEN' for pensjonsrelaterte ytelser
      max_length: 8

    - name: tidspkt_reg
      col_data_type: datetime
      description: Tidspunktet for når raden er lastet inn i tabellen.

- name: t_vent_stoppnivaa
  table_type: fak
  description: Stoppnivå er et begrep i Oppdragssystemet som brukes for nedbryting av beregninger. En beregning kan brytes ned i f.eks. perioder med tilhørende forfallsdato gjelde forskjellige mottakere eller kan gjelde ulike saker (f.eks sykepenger til én bruker men gjelder flere forhold. Stoppnivå id sammen med beregnings id vil unikt identifisere et stoppnivå for en beregning
  check_col: tidspkt_reg
  order_cols: 
    - beregnings_id
    - stoppnivaa_id
  cols:
    - name: beregnings_id
      col_data_type: INTEGER
      description: Identifikator for beregninger i Oppdragssystemet.
      mode: REQUIRED

    - name: stoppnivaa_id
      col_data_type: INTEGER
      description: Identifikator for stoppnivå i Oppdragssystemet. Stoppnivaa_id sammen med beregnings_id vil unikt identifisere et stoppnivå for en beregning. Ikke nødvendigvis inkrementelt med 1.
      mode: REQUIRED

    - name: oppdrags_id
      col_data_type: INTEGER
      description: Identifikator på utbetalingsoppdraget unik identifikator som Oppdragssystemet oppretter når man mottar ett vedtak til utbetaling fra fagsystem.

    - name: fagsystem_id
      col_data_type: STRING
      description: Identifikator fra vedtaksløsningen som har avlevert ett utbetalingsoppdrag
      max_length: 30

    - name: type_skatt
      description: Angir om det er beregnet skatt med prosenttrekk eller tabelltrekk.
      col_data_type: STRING
      max_length: 4

    - name: kode_fagomraade
      col_data_type: STRING
      description: En kode som angir selve ytelsen som beregningen gjelder f.eks. 'AAP' for arbeidsavklaringspenger
      max_length: 8

    - name: dato_periode_fom
      col_data_type: DATE
      description: Startdatoen stoppnivået gjelder for. Sammen med dato_periode_tom utgjør dette perioden stoppnivået gjelder for.
    
    - name: dato_periode_tom
      col_data_type: DATE
      description: Sluttdatoen stoppnivået gjelder for. Sammen med dato_periode_fom utgjør dette perioden stoppnivået gjelder for.
    
    - name: dato_forfall
      col_data_type: DATE
      description: Dato for når stoppnivået skal utbetales.

    - name: dato_overfores
      col_data_type: DATE
      description: Dato for når stoppnivået er planlagt overført til reskontro

    - name: tidspkt_reg
      col_data_type: DATETIME
      description: Tidspunktet for når raden er lastet inn i tabellen.

- name: t_vent_stoppstatus
  table_type: fak
  description: Status for stoppnivå. Stoppstatus er synonymt med ventestatus.
  check_col: tidspkt_reg
  order_cols: 
    - beregnings_id
    - stoppnivaa_id
    - lopenr
  cols:         
    - name: beregnings_id
      col_data_type: INTEGER
      description: Identifikator for beregninger i Oppdragssystemet.
      mode: REQUIRED
  
    - name: stoppnivaa_id
      col_data_type: INTEGER
      description: Identifikator for stoppnivå i Oppdragssystemet
      mode: REQUIRED
  
    - name: kode_ventestatus
      col_data_type: STRING
      description: Kode for status på stoppnivået f.eks OVFO (for 'Overført til UR')
      max_length: 4
  
    - name: lopenr
      col_data_type: INTEGER
      description: Løpenummer. Tall som er >= 1 hopper med steg += 1, 9999 markerer gjeldende ventestatus
      mode: REQUIRED
  
    - name: tidspkt_reg
      col_data_type: DATETIME
      description: Tidspunktet for når raden er lastet inn i tabellen.

- name: t_vent_detalj
  table_type: fak
  description: .
  check_col: tidspkt_reg
  order_cols: 
    - beregnings_id
    - stoppnivaa_id
    - linjenr
  cols:         
    - name: beregnings_id
      col_data_type: integer
      description: Identifikator for beregninger i Oppdragssystemet.
      mode: REQUIRED
      
    - name: stoppnivaa_id
      col_data_type: integer
      description: Identifikator for stoppnivå i Oppdragssystemet
      mode: REQUIRED

    - name: linjenr
      col_data_type: integer
      description: En del av unik identifikator i tabellen
      mode: REQUIRED

    - name: belop
      col_data_type: string
      description: Beløp

    - name: trekkvedtak_id
      col_data_type: integer
      description: Identifikator for trekktype som beløp gjelder for

    - name: tidspkt_reg
      col_data_type: datetime
      description: Tidspunktet for når raden er lastet inn i tabellen.

- name: t_faggruppe
  table_type: dim
  description: Kodeverk for faggruppe. En faggruppe består av flere fagområder hvor man ønsker en samlet felles skatt-og trekkberegning. F.eks. pensjonsrelaterte ytelser
  cols:
    - name: kode_faggruppe
      col_data_type: string
      description: Kode for faggruppe. F.eks. 'PEN' for pensjonsrelaterte ytelser
      mode: required
      max_length: 8
            
    - name: navn_faggruppe
      col_data_type: STRING
      description: Navn/beskrivelse på faggruppe
      max_length: 50
  
    - name: tidspkt_reg
      col_data_type: DATETIME
      description: Tidspunktet for når raden er lastet inn i tabellen.

- name: t_fagomraade
  table_type: dim
  description: Kodeverk for fagområde. Fagområde angir selve ytelsen f.eks. arbeidsavklaringspenger
  cols: 
    - name: kode_fagomraade
      col_data_type: STRING
      description: Kode for fagområde. F.eks. 'AAP' for arbeidsavklaringspenger
      mode: REQUIRED
      max_length: 8
  
    - name: navn_fagomraade
      col_data_type: STRING
      description: Navn/beskrivelse på fagområde
      max_length: 50
  
    - name: kode_faggruppe
      col_data_type: STRING
      description: Kode for faggruppe f.eks. 'ARBYT' for arbeidsrelaterte ytelser
      max_length: 8
  
    - name: tidspkt_reg
      col_data_type: DATETIME
      description: Tidspunktet for når raden er lastet inn i tabellen.

- name: t_vent_statuskode
  table_type: dim
  description: Kodeverk for ventestatus/stoppstatus. En ventestatus angir statusen på et stoppnivå i Oppdragssystemet
  cols: 
    - name: kode_ventestatus
      col_data_type: STRING
      description: Kode for ventestatus. F.eks OVFO (for 'Overført til UR'
      mode: REQUIRED
      max_length: 4
  
    - name: beskrivelse
      col_data_type: STRING
      description: Beskrivelse av ventestatuskode eks 'Overført til UR'
      max_length: 40
  
    - name: tidspkt_reg
      col_data_type: DATETIME
      description: Tidspunktet for når raden er lastet inn i tabellen.