tables:
- name: t_faggruppe
  table_type: dim
  description: Kodeverk for faggruppe. En faggruppe består av flere fagområder hvor man ønsker en samlet felles skatt-og trekkberegning. F.eks. pensjonsrelaterte ytelser
  cols:
    - name: kode_faggruppe
      col_data_type: string
      description: Kode for faggruppe. F.eks. 'PEN' for pensjonsrelaterte ytelser
      mode: required
      max_length: 8
