apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
spec:
  receivers:
  - name: utsikt-slack-receiver
    slackConfigs:
    - actions:
      - text: 'Runbook :green_book:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ (index .Alerts 0).Annotations.runbook_url
          }}{{ end }}'
      - text: 'Query :mag:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ (index .Alerts 0).GeneratorURL }}{{ end
          }}'
      - text: 'Dashboard :grafana:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ (index .Alerts 0).Annotations.dashboard_url
          }}{{ end }}'
      - text: 'Silence :no_bell:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ .ExternalURL }}/#/silences/new?filter=%7B{{
          range .CommonLabels.SortedPairs }}{{ if ne .Name "alertname" }}{{ .Name
          }}%3D"{{ .Value }}"%2C%20{{ end }}{{ end }}alertname%3D"{{ .CommonLabels.alertname
          }}"%7D{{ end }}'
      - text: "{{ if .CommonAnnotations.link_text }}{{ .CommonAnnotations.link_text
          }}{{ else }}Link{{ end }} :link:"
        type: button
        url: '{{ if eq .Status "firing" }}{{ .CommonAnnotations.link_url }}{{ end
          }}'
      apiURL:
        key: apiUrl
        name: slack-webhook
      channel: "#utsikt-ops"
      color: '{{ template "slack.color" . }}'
      httpConfig:
        proxyUrl: http://webproxy.nais:8088
      iconEmoji: ":scream:"
      sendResolved: true
      text: '{{ template "slack.text" . }}'
      title: '{{ template "slack.title" . }}'
      username: Alertmanager nav-dev-fss
  - name: utsikt-slack-receiver-firing-only
    slackConfigs:
    - actions:
      - text: 'Runbook :green_book:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ (index .Alerts 0).Annotations.runbook_url
          }}{{ end }}'
      - text: 'Query :mag:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ (index .Alerts 0).GeneratorURL }}{{ end
          }}'
      - text: 'Dashboard :grafana:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ (index .Alerts 0).Annotations.dashboard_url
          }}{{ end }}'
      - text: 'Silence :no_bell:'
        type: button
        url: '{{ if eq .Status "firing" }}{{ .ExternalURL }}/#/silences/new?filter=%7B{{
          range .CommonLabels.SortedPairs }}{{ if ne .Name "alertname" }}{{ .Name
          }}%3D"{{ .Value }}"%2C%20{{ end }}{{ end }}alertname%3D"{{ .CommonLabels.alertname
          }}"%7D{{ end }}'
      - text: "{{ if .CommonAnnotations.link_text }}{{ .CommonAnnotations.link_text
          }}{{ else }}Link{{ end }} :link:"
        type: button
        url: '{{ if eq .Status "firing" }}{{ .CommonAnnotations.link_url }}{{ end
          }}'
      apiURL:
        key: apiUrl
        name: slack-webhook
      channel: "#utsikt-ops"
      color: '{{ template "slack.color" . }}'
      httpConfig:
        proxyUrl: http://webproxy.nais:8088
      iconEmoji: ":scream:"
      sendResolved: false
      text: '{{ template "slack.text" . }}'
      title: '{{ template "slack.title" . }}'
      username: Alertmanager nav-dev-fss
  route:
    groupBy:
    - alertname
    groupInterval: 5m
    groupWait: 10s
    matchers:
    - matchType: "="
      name: namespace
      value: utsikt
    - matchType: "!="
      name: alert_type
      value: custom
    receiver: utsikt-slack-receiver
    repeatInterval: 1h
    routes:
    - continue: false
      matchers:
      - matchType: "="
        name: send_resolved
        value: 'false'
      receiver: utsikt-slack-receiver-firing-only
    - receiver: utsikt-slack-receiver