apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: db2-til-bq-init-os
  namespace: utsikt
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  schedule: "0 6 4 10 *" # Runs on the 4th of October. Pls delete me before October 2027.
  resources:
    limits:
      cpu: 600m
      memory: 4Gi
    requests:
      cpu: 600m
      memory: 2Gi
  webproxy: true
  filesFrom:
    - secret: service-account-key
    - secret: db2-license-11
      mountPath: /var/run/secrets/db2-license
  envFrom:
    - secret: oppdrag-credentials
    - secret: google-application-credentials