apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: db2-til-bq-init
  namespace: utsikt
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  schedule: "0 6 30 1 *" # Runs 1 every year on the 30th of january. Pls delete me in 2026.
  failedJobsHistoryLimit: 0 #vil fjerne historikken så vi slipper å få alert hver time
  resources:
    limits:
      cpu: 600m
      memory: 4Gi
    requests:
      cpu: 600m
      memory: 2Gi
  webproxy: true
  filesFrom:
    - secret: service-account-key
    - secret: db2-license-11
      mountPath: /var/run/secrets/db2-license
  envFrom:
    - secret: oppdrag-credentials
    - secret: google-application-credentials
