apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: venteregister-data
  namespace: utsikt
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  schedule: "0 6 * * *" # Runs 6 in the morning
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
  webproxy: true
  filesFrom:
    - secret: service-account-key
    - secret: db2-license-11
      mountPath: /var/run/secrets/db2-license
  envFrom:
    - secret: oppdrag-q1-credentials
  env:
    # Db2
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "OS231Q1"
