name: Deploy alerts

on: [push]

jobs:
    deploy:
        name: Deploy to dev and prod
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            actions: read

        steps:
            - name: Check out repository code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: Deploy to DEV
              uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
              env:
                  CLUSTER: "dev-fss"
                  RESOURCE: .nais/alert.yaml
            - name: Deploy to PROD
              uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
              env:
                  CLUSTER: "prod-fss"
                  RESOURCE: .nais/alert.yaml
