name: Deploy alerts

on: [push]

jobs:
    deploy:
        name: Deploy to dev and prod
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            actions: read

        steps:
            - name: Check out repository code
              uses: actions/checkout@v5
            - name: Deploy to DEV
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: "dev-fss"
                  RESOURCE: .nais/alert.yaml,.nais/alert-config.yaml
